controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: false
    minReplicas: 1


## The following addons are not really necessarily for a homelab setup
## Enable if you have enough CPU/Memory resources and need them for some purpose 
dex:
  enabled: false

redis:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1

configs:
  secret:
    argocdServerAdminPassword: $2a$10$6Oa1o/Y/5xjDk2dQCQ8F9uDCqm9w8BJEp7ZjI0.SvmZqIXXpHFyQW
  repositories:
    podinfo-helm-repo:
      url: https://stefanprodan.github.io/podinfo
      name: podinfo
      type: helm
    app-manifests-repo:
      url: https://github.com/slashr/app-manifests.git
      name: app-manifests
      type: git

  ingress:
    enabled: true
    annotations:
    # This lets cert-manager identify which Ingresses to generate a cert for
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: "nginx"

    # -- List of ingress hosts
    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    hosts:
      - "argo.akashnair.com"

    # -- List of ingress paths
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls 
        hosts:
          - "argo.akashnair.com"
